### ISSUE TITLE
Dataset

### ISSUE THREAD

**Issue by YYDS-cc** [jzhzhang/3DAwareNav#1]
Excellent work！
This is my first time working with datasets for object navigation and I have a few questions to ask. According to the readme, I am downloading the habitat zip from the (MP3D) dataset, how much storage space does this require, and furthermore, how do I split the downloaded dataset into the form of a readme?

**Comment by jzhzhang** [comment]
Thank you for your interest in our work! I believe the scene dataset may require approximately 30-40GB of storage (the episode dataset won't occupy much space). Additionally, you don't need to be worried about the training and validation data as it has already been separated in the episode dataset.

**Comment by YYDS-cc** [comment]
Thanks for the reply, I have downloaded and unzipped habitat.zip, which has 90 scenes（20.8GB）, but I didn't find any information about the episode dataset in the official download file. How can I download it?

**Comment by jzhzhang** [comment]
The details can be found in [habitat-lab dataset](https://github.com/facebookresearch/habitat-lab/blob/main/DATASETS.md), and the you should download the [Matterport3D objectnav_mp3d_v1.zip](https://dl.fbaipublicfiles.com/habitat/data/datasets/objectnav/m3d/v1/objectnav_mp3d_v1.zip)

**Comment by YYDS-cc** [comment]
Thank you so much!
