### ISSUE TITLE
Questions about success criteria in the task `yaml` file

### ISSUE THREAD

**Issue by ResearcherYan** [jzhzhang/3DAwareNav#10]
Hello, Dr. Zhang. I have some questions about the success criteria in the task `yaml` file.

After observing the evaluation results, I found in some cases even the agent finds and reaches the goal correctly, the function `habitat.Env.get_metrics()` still returns `success=0`. So I checked the success criteria in the task file.

Then I found [the task file of 3DAwareNav](https://github.com/jzhzhang/3DAwareNav/blob/main/envs/habitat/configs/tasks/challenge_objectnav2021.local.rgbd.yaml#L45) and [the one of Object-Goal-Navigation](https://github.com/devendrachaplot/Object-Goal-Navigation/blob/master/envs/habitat/configs/tasks/objectnav_gibson.yaml#L37) is different in success criteria. The former file defines `SUCCESS_DISTANCE = 0.1` while the latter one designates `SUCCESS_DISTANCE = 0.2`. What's more, 3DAwareNav uses "distance to view points" as the metric `DISTANCE_TO_GOAL` and Object-Goal-Navigation utilizes "distance to goal" directly.

Could you please let us know **why 3DAwareNav uses "distance to view points" as the `DISTANCE_TO_GOAL` metric and narrows the success distance threshold?**

**Comment by ResearcherYan** [comment]
Plus, the default `MOVE_FORWARD` step size is 0.25m. So I guess it's a little bit strict for the agent to reach the view point within 0.1m when its basic step size is 0.25m?

**Comment by jzhzhang** [comment]
We directly follow the default setting of our baseline [PONI](https://github.com/srama2512/PONI/blob/30682c2bdcd820eec8f72043b2579eb045d547bf/hlab/transfer_configs/objectnav_mp3d.yaml#L4) for fair comparison.  However the setting of ObjectNav changes after the updating of the benchmark, you can see the latest configuration in [Habitat-challenge](https://aihabitat.org/challenge/2022/)

**Comment by ResearcherYan** [comment]
Thanks for your quick reply. According to the link you provided, an episode is deemed successful if on calling the STOP action, **the agent is within 1.0m Euclidean distance from any instance of the target object category AND the object can be viewed by an oracle from that stopping position** by turning the agent or looking up/down. I guess this is different from the task file settings?

**Comment by ResearcherYan** [comment]
I think I'm clear about the success criteria now. Thank you, Dr. Zhang.

Both the habitat-challenge 2021 and 2022 set the distance threshold as **1.0m** in their website instructions. But in [the paper of HM3D](https://arxiv.org/pdf/2109.08238), section 4.1 "Experimental setup" mentions that: The agent succeeds if it reaches within 0.2m of the goal location and executes $\text{STOP}$, which aligns with the [Object-Goal-Navigation](https://github.com/devendrachaplot/Object-Goal-Navigation) setups. So I guess when it comes to code implementations, `SUCCESS_DISTANCE = 0.2` is what the HM3D teams really do. And I get it that 3DAwareNav's task settings mainly inherit from PONI, which are a little bit different from the habitat-challenge settings.

**Comment by jzhzhang** [comment]
Your understanding is correct. Feel free to reopen this issue if you have any further questions related to this topic.
