### ISSUE TITLE
Environmental issues when I run the code

### ISSUE THREAD

**Issue by peakfly** [jzhzhang/3DAwareNav#2]
Hello，Thanks for your work.I had some problems when I run the code
What's the version of pytorch, torchvision,cudatoolkit and detectron2?
Looking forward to your reply.

**Comment by jzhzhang** [comment]
You can follow the instructions of Habitat-sim(v0.2.2)  and habitat-lab (v0.2.2) to finish the installation, which will also include install torch-related lib. And then you can install detectron2 based on your torch and cuda version by following [detectron2 installation guide](https://detectron2.readthedocs.io/en/latest/tutorials/install.html#install-pre-built-detectron2-linux-only). Another option is to directly install detectorn2 from its source code.

**Comment by Zhang-Yuefeng** [comment]
您的邮件已收到！谢谢！--------------------------------------------This is an automatic reply, confirming that your e-mail was received.Thank you

**Comment by peakfly** [comment]
Thank you! I have followed the instructions of Habitat-sim (v0.2.2) and habitat-lab (v0.2.2).I have also installed detectorn2 from its source code by following
`git clone https://github.com/facebookresearch/detectron2.git`
`python -m pip install -e detectron`.
The conda list is as follows：
|  Name | Version | 
| :-----:| :----: | 
| python | 3.7.16 | 
| torch | 1.13.1 | 
| nvidia-cuda-runtime-cu11| 11.7.99 |
| detectron2|0.6 |
|habitat |0.2.2|
|habitat-sim | 0.2.2|

But when I run the `sh sh_train_mp3d.sh`,the error occured:
![image](https://github.com/jzhzhang/3DAwareNav/assets/68849846/d2c48d8b-b0c3-4a4f-ac8b-c8838b138b92)
The chatgpt said it was a problem with the python version.The python version should >=3.8.
I have no idea.

**Comment by peakfly** [comment]
Could you give me some advice on the version of pytorch,cuda and python ?   Thank you!
