### ISSUE TITLE
model and evaluation about Gibson dataset

### ISSUE THREAD

**Issue by zenght** [jzhzhang/3DAwareNav#6]
Thank you for sharing. I would like to know if it is possible to provide the model trained on the Gibson data set and the eval code.

**Comment by jzhzhang** [comment]
We do not have plans to update the Gibson code in this repository. Instead, you can directly utilize the 2D semantic predictor from https://github.com/devendrachaplot/Object-Goal-Navigation and train our exploration and identification policies.
