### ISSUE TITLE
Weights for explore policy and identify policy

### ISSUE THREAD

**Issue by Cassie-Lim** [jzhzhang/3DAwareNav#7]
Hi, thanks for the great work. Could you please release the weights for `explore_policy` and `identify_policy`?

**Comment by jzhzhang** [comment]
Thank you for your interest in our project. Our weights are not publicly accessible. If you need our weights for non-commercial purposes, please contact me via email at zhngjizh@gmail.com, and I will provide them to you.

**Comment by Cassie-Lim** [comment]
Thanks for your reply :D.
