### ISSUE TITLE
Evaluation process never finishes

### ISSUE THREAD

**Issue by ResearcherYan** [jzhzhang/3DAwareNav#9]
Hi, Dr. Zhang. Here is my `sh_eval.sh`:

```sh
python main.py --auto_gpu_config 0  -n 10  --num_processes_per_gpu 5 \
    --sem_gpu_id_list "0,1"  --policy_gpu_id "cuda:3"  --sim_gpu_id "0,1" \
    --split val  --backbone_2d "rednet" \
    --task_config "tasks/challenge_objectnav2021.local.rgbd.yaml"  --dataset "mp3d" \
    --num_sem_categories 22 \
    --print_images 0  -d ./tmp  --exp_name eval_3D_stop_policy_rednet \
    --eval 1 \
    --load_explore weight/periodic_explore_3d.pth \
    --load_identify weight/periodic_identify_3d.pth
```

As you can see, I use 2 gpu to run 10 processes. Since `val` dataset has 11 scenes, the code automatically allocates the first two scenes `2azQ1b91cZZ.glb` and `8194nk5LbLH.glb` to the first process. Under such settings, my evaluation process seems never come to an end. Finally the code will load `2azQ1b91cZZ.glb` and `8194nk5LbLH.glb` again and again, as shown below.

![image](https://github.com/user-attachments/assets/a81e0314-f069-46a9-8780-457edcfc4240)

![image](https://github.com/user-attachments/assets/e9af1ad9-2eed-4f4e-9ece-25cbb2031f48)

![image](https://github.com/user-attachments/assets/74169a5f-a0ff-4b56-b3fb-c23645ec7971)

![image](https://github.com/user-attachments/assets/48beec18-6ca6-47eb-aceb-4460b9adcbfb)

Not sure if this is a bug or something?

What's more, the total finished episode num remains as `1985` but the `succ` and `dtg` metrics are still changing. Why does the episode num keep still?

![image](https://github.com/user-attachments/assets/55d048ba-a016-4282-b3b2-b088d7b1422d)

If you know why these situations happened, please let me know. Thank you!!

**Comment by jzhzhang** [comment]
Our evaluation setup follows the object-goal environment defined in [ObjectGoalNav](https://github.com/devendrachaplot/Object-Goal-Navigation/blob/master/envs/habitat/objectgoal_env.py). Specifically, it checks whether all episodes within a given scene have been completed before transitioning to the next scene.

In the [main.py](https://github.com/jzhzhang/3DAwareNav/blob/a67f842b65f97368fb700fc7a264610e07a20198/main.py#L516) script, the program terminates once the episodes for all scenes are finished. However, the environment continues to switch between scenes, though these scenes are marked as repeated.

I suspect that one or more processes may have become stuck or suspended. Given the number of episodes, I believe the results have already converged.

**Comment by ResearcherYan** [comment]
I guess you're right. It might be some weird stucking problems that can't be explained. The episode num didn't increase but the succ and dtg changed. If the program went normally, this could never happen.
